---
- name: Obtener token del master desde hostvars
  set_fact:
    k3s_token: "{{ hostvars['k8s-master'].k3s_token }}"
    k3s_server_url: "{{ hostvars['k8s-master'].k3s_server_url }}"

- name: Instalar K3s agent en el worker
  shell: |
    curl -sfL https://get.k3s.io | \
    K3S_URL="{{ k3s_server_url }}" \
    K3S_TOKEN="{{ k3s_token }}" \
    sh - 
  args:
    creates: /usr/local/bin/k3s-agent
